image: nixos/latest
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://github.com/chiefnoah/zettelkasten.git
environment:
  site: chiefnoah.srht.site
tasks:
  - setup: |
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use srid
      nix-env -if https://github.com/srid/emanote/archive/refs/heads/master.tar.gz
  - gen: |
      [ -d "./z" ] && cd z || cd zettelkasten
      emanote --layers .deploy/github gen .output
      cd .output
      tar -cvzf ../../site.tar.gz .
  - deploy: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz

