image: nixos/latest
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://github.com/chiefnoah/zettelkasten.git
environment:
  site: chiefnoah.srht.site
tasks:
  - setup: |
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use srid
      nix-env -if https://github.com/srid/neuron/archive/master.tar.gz
  - gen: |
      [ -d "./z" ] && cd z || cd zettelkasten
      neuron gen
      cd .neuron/output
      tar -cvzf ../../../site.tar.gz .
  - deploy: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz

